version: '3'
services:
  postgresql:
    image: postgres:latest
    restart: always
    ports: 
      - "${PG_PORT}:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=rappidb"
    volumes: 
      - ${DBDATA_DIR}:/var/lib/postgresql/data
  users:
    image: "node:latest"
    restart: always
    ports:
      - "${USERS_PORT}:3001"
    environment:
      - "DB_NAME=rappidb"
      - "DB_USER=postgres"
      - "DB_PASS=password"
      - "DB_HOST=postgresql"
    volumes:
      - "${USERS_DIR}:/Code/users"
    entrypoint: ["sleep", "5000"]
    working_dir: /Code/users
  
  stores:
    image: node:latest
    restart: always
    ports: 
      - "${STORES_PORT}:4001"
    environment:
      - "DB_NAME=rappidb"
      - "DB_USER=postgres"
      - "DB_PASS=password"
      - "DB_HOST=postgresql"
    volumes:
      - "${STORES_DIR}:/Code/stores"
    entrypoint: ["sleep", "5000"]
    working_dir: /Code/stores

  orders:
    image: node:latest
    restart: always
    ports: 
      - "${ORDERS_PORT}:5001"
    environment:
      - "DB_NAME=rappidb"
      - "DB_USER=postgres"
      - "DB_PASS=password"
      - "DB_HOST=postgresql"
    volumes:
      - "${ORDERS_DIR}:/Code/orders"
    entrypoint: ["sleep", "5000"]
    working_dir: /Code/orders



